config/routes.rb
Rails.application.routes.draw do
  mount Shoppe::Engine => "/shoppe"

  
  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"
  root to: "products#index"
  
  post "product/:permalink", to: "products#buy"
  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private

  def current_order
    @current_order ||= begin
      if has_order?
        @current_order
      else
        order = Shoppe::Order.create(:ip_address => request.ip)
        session[:order_id] = order.id
        order
      end
    end
  end

  def has_order?
    !!(
      session[:order_id] &&
      @current_order = Shoppe::Order.includes(:order_items => :ordered_item).find_by_id(session[:order_id])
    )
  end

  helper_method :current_order, :has_order?
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def destroy
        current_order.destroy
        session[:order_id] = nil
        redirect_to root_path, :notice => "Basket emptied successfully."
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
        @products = @products.group_by(&:product_category)
    end

    def show
        @product = Shoppe::Product.root.find_by_permalink(params[:permalink])
    end
    
    def buy
        @product = Shoppe::Product.root.find_by_permalink!(params[:permalink])
        current_order.order_items.add_item(@product, 1)
        redirect_to product_path(@product.permalink), :notice => "Product has been added successfuly!"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>M-Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <br/>
  <div class="row">
    <div class="col-sm-4">
      <%= image_tag("logo.jpg", width: "200") %>
    </div>
    <div class="col-sm-8">
      <h1 style="font-size:80px"><span class="label label-success">A.S. Store</span></h1>
    </div>
  </div>
  <br/>
  <% if current_order %>
  <div class="well">
    You have <%= pluralize current_order.total_items, 'item'%> in your basket which cost
    <%= number_to_currency current_order.total_before_tax %>.
    <button type="button" class="btn btn-info"><%= link_to "View basket", basket_path, style:"color:#FFF" %></button>
  </div>
  <% end %>
  <%= flash[:notice] %>
  <%= yield %>
</div>
</body>
</html>

app/views/orders/_items.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <td>Quantity</td>
      <td>Product</td>
      <td>Total</td>
    </tr>
  </thead>
  <tbody>
    <% order.order_items.each do |item| %>
    <tr>
      <td><%= item.quantity %></td>
      <td><%= item.ordered_item.full_name %></td>
      <td><%= number_to_currency item.total %></td>
    </tr>
    <% end %>

    <% if order.delivery_service %>
    <tr>
      <td></td>
      <td><%= order.delivery_service.name %></td>
      <td><%= number_to_currency order.delivery_price %></td>

    </tr>
    <% end %>

  </tbody>
  <tfoot>
    <tr>
      <td colspan='2'>Total</td>
      <td><%= number_to_currency order.total %></td>
    </tr>
  </tfoot>
</table>

app/views/orders/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Your basket</h2>
    </div>
    <div class="col-lg-12">
        <%= render 'items', :order => current_order %>
    </div>
    <div class="col-lg-12 text-center">
        <button type="button" class="btn btn-lg btn-danger "><%= link_to 'Empty basket', basket_path, :method => :delete, style:"color:#FFF" %></button>
    </div>
</div>

app/views/products/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Products</h2>
    </div>
    
    <% @products.each do |category, products| %>
    <div class="col-sm-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><%= category.name %></h3>
            </div>
            <div class="panel-body">
                <% products.each do |product| %>
                <div class="row">
                    <div class="col-sm-6">
                        <ul>
                        
                            <li>
                              <h4><%= link_to product.name, product_path(product.permalink) %></h4>
                              <p><%= product.short_description %></p>
                              <p><b>Price:</b> <%= number_to_currency product.price %></p>
                            </li>
                        </ul>
                    </div>
                    <div class="col-sm-6">
                        <%= image_tag product.default_image.path, :width => '80px', :style => "float:right" %>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/products/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header"><%= @product.name %></h2>
    </div>
    
    <div class="col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"><%= @product.short_description %></h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-6">
                        <p>
                          <b><%= number_to_currency @product.price %></b>
                          <button type="button" class="btn btn-sm btn-warning"><%= link_to "Add to basket", product_path(@product.permalink), :method => :post, style:"color:#FFF" %></button>
                        </p>
                        <hr>
                        <%= simple_format @product.description %>
                        <hr>
                    </div>
                    <div class="col-sm-6">
                        <% if @product.default_image %>
                            <%= image_tag @product.default_image.path, :width => '100px', :style => "float:right" %>
                        <% end %>
                    </div>
            </div>
        </div>
    </div>
</div>
<br/>
<button type="button" class="btn btn-primary"><%= link_to "Back to list", root_path, style:"color:#FFF" %></button>